/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NcmineRouteImport } from './routes/ncmine'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddonIdRouteImport } from './routes/addon.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NcmineRoute = NcmineRouteImport.update({
  id: '/ncmine',
  path: '/ncmine',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonIdRoute = AddonIdRouteImport.update({
  id: '/addon/$id',
  path: '/addon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/ncmine': typeof NcmineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/addon/$id': typeof AddonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/ncmine': typeof NcmineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/addon/$id': typeof AddonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/ncmine': typeof NcmineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/addon/$id': typeof AddonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/ncmine'
    | '/sitemap.xml'
    | '/addon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/favoritos' | '/ncmine' | '/sitemap.xml' | '/addon/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favoritos'
    | '/ncmine'
    | '/sitemap.xml'
    | '/addon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FavoritosRoute: typeof FavoritosRoute
  NcmineRoute: typeof NcmineRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AddonIdRoute: typeof AddonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncmine': {
      id: '/ncmine'
      path: '/ncmine'
      fullPath: '/ncmine'
      preLoaderRoute: typeof NcmineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addon/$id': {
      id: '/addon/$id'
      path: '/addon/$id'
      fullPath: '/addon/$id'
      preLoaderRoute: typeof AddonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FavoritosRoute: FavoritosRoute,
  NcmineRoute: NcmineRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AddonIdRoute: AddonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
